INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Java Programming','IT11',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Data Structure and Algorithms ','IT12',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Object Oriented Software Engineering','IT13',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,' Operating System Concepts ','IT14',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Network Technologies','IT15',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Open Course 1','OC11',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Open Course 2','OC12',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Practical','IT11L',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Mini Project','ITC11',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Soft Skills - I','SS11',1,1);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Human Rights -I','191',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Introduction to Cyber Security- I','192',1,1),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,' Python Programming','IT21',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Software Project Management','IT22',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Optimization Techniques','MT21',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Advanced Internet Technologies','IT23',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Advanced DBMS','IT24',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Open Course 3','OC21',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Open Course 4','OC22',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Practical','IT21L',1,2);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Mini Project','ITC21',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Soft Skills - II','SS21',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Human Rights -II','291',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Introduction to Cyber Security - II','292',1,2),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Mobile Application Development','IT31',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Data Warehousing and Data Mining','IT32',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Software Testing and Quality Assurance','IT33',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Knowledge Representation & Artificial Intelligence - ML, DL','IT34',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Cloud Computing','IT35',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Open Course 5','OC11',3,3);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Open Course 6','OC12',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Practical','IT31L',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Mini Project','ITC31',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Soft Skills- III','SS11',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Introduction to Cyber Security- III','392',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Skill Development - I','394',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Introduction to Constitution','395',3,3),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'DevOps ','IT41',3,4),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'PPM and OB','BM41',3,4),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Project','ITC41',3,4);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Introduction to Cyber Security- IV','492',3,4),
	 (NULL,NULL,NULL,NULL,NULL,'2020','Computer',1,'Skill Development - II','494',3,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Managerial Accounting','101-GC ? 01',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Organizational Behaviour','102-GC ? 02',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Economic Analysis for Business Decisions','103-GC ? 03',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Business Research Methods','104-GC ? 04',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Management Fundamentals','107-GE - UL - 01',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Indian Economy','108-GE - UL - 02',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Entrepreneurship Development','109-GE - UL - 03',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Essentials of Psychology for Managers','110-GE - UL - 04',2,1);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Legal Aspects of Business','111-GE - UL - 05',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Demand Analysis & Forecasting','112-GE - UL - 06',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Verbal Communication Lab','113-GE - IL - 01',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Enterprise Analysis & Desk Research','114-GE - IL - 02',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Selling & Negotiation Skills Lab','115-GE - IL - 03',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'MS Excel','116-GE - IL - 04',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Business Systems & Procedures','117-GE - IL - 05',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Managing Innovation','118-GE ? IL- 06',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Foreign Language ? I','119-GE ? IL- 07',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Human Rights - I','191',2,1);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Introduction to Cyber Security - I','192',2,1),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Marketing Management','201-GC ? 07',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Financial Management','202-GC ? 08',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Human Resources Management','203-GC ? 09',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Operations & Supply Chain Management','204-GC ? 10',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Marketing Research','205-SC ? MKT- 01',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Consumer Behaviour','206-SC ? MKT- 02',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Financial Markets and Banking Operations','205-SC ? FIN - 01',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Personal Financial Planning','206-SC ? FIN - 02',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Competency Based Human Resource Management','205-SC ? HRM ? 01',2,2);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Employee Relations & Labour Legislation','206-SC ? HRM ? 02',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Services Operations Management - I','205-SC ? OSCM - 01',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Supply Chain Management','206-SC ? OSCM - 02',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Basic Business Analytics using R','205-SC ? BA - 01',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Data Mining','206-SC ? BA - 02',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Contemporary Frameworks in Management','GE - UL - 07',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Geopolitics & World Economic Systems','GE - UL - 08',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Start Up and New Venture Management','GE - UL - 09',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Qualitative Research Methods','GE - UL - 10',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Business, Government & Society','GE - UL - 11',2,2);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Business Process Re-engineering','GE - UL - 12',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Written Analysis and Communication Lab','GE ? IL - 08',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Industry Analysis & Desk Research','GE ? IL - 09',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Entrepreneurship Lab','GE ? IL - 10',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'SPSS','GE ? IL - 11',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Foreign Language ? II','GE ? IL - 12',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Integrated Marketing Communications','217-SE ? IL - MKT- 01',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Product & Brand Management','218-SE ? IL - MKT- 02',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Personal Selling Lab','219-SE ? IL - MKT- 03',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Digital Marketing - I','220-SE ? IL - MKT- 04',2,2);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Marketing of Financial Services - I','221-SE ? IL - MKT- 05',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Marketing of Luxury Products','222-SE ? IL - MKT- 06',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Securities Analysis & Portfolio Management','217-SE ? IL - FIN - 01',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Futures and Options','218-SE ? IL - FIN - 02',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Direct Taxation','219-SE ? IL - FIN - 03',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Financial Reporting','220-SE ? IL - FIN - 04',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Retail Credit Management- Lending & Recovery','221-SE ? IL - FIN - 05',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Banking Laws & Regulations','222-SE ? IL - FIN - 06',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Fundamentals of Life Insurance ? Products and Underwriting','223-SE ? IL - FIN - 07',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'General Insurance - Health and Vehicle','224-SE ? IL - FIN - 08',2,2);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Labour Welfare','217-SE ? IL - HRM - 01',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Lab in Recruitment and Selection','218-SE ? IL - HRM - 02',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Learning and Development','219-SE ? IL - HRM - 03',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Public Relations & Corporate Communications','220-SE ? IL - HRM - 04',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'HR Analytics','221-SE ? IL - HRM - 05',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Conflict and Negotiation Management','222-SE ? IL - HRM - 06',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Planning & Control of Operations','217-SE ? IL - OSCM - 01',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Productivity Management','218-SE ? IL - OSCM - 02',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Inventory Management','219-SE ? IL - OSCM - 03',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Theory of Constraints','220-SE ? IL - OSCM - 04',2,2);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Quality Management Standards','221-SE ? IL - OSCM - 05',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Service Value Chain Management','222-SE ? IL - OSCM - 06',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Marketing Analytics','217-SE ? IL - BA - 01',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Retailing Analytics','218-SE ? IL - BA - 02',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Workforce Analytics','219-SE ? IL - BA - 03',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Tableau','220-SE ? IL - BA - 04',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Data Warehousing Project Life Cycle Management','221-SE ? IL - BA - 05',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Human Rights - II','291',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Introduction to Cyber Security - II','292',2,2),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Strategic Management','301-GC ? 11',4,3);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Decision Science','302-GC ? 12',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Summer Internship Project*','303-GC ? 13',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Services Marketing','304-SC ? MKT- 03',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Sales & Distribution Management','305-SC ? MKT- 04',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Advanced Financial Management','304-SC ? FIN - 03',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'International Finance','305-SC ? FIN - 04',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Strategic Human Resource Management','304-SC ? HRM - 03',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'HR Operations','305-SC ? HRM - 04',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Services Operations Management - II','304-SC ? OSCM - 03',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Logistics Management','305-SC ? OSCM - 04',4,3);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Advanced Statistical Methods using R','304-SC ? BA - 03',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Machine Learning & Cognitive intelligence using Python','305-SC ? BA - 04',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'International Business Economics','306-GE - UL - 13',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'International Business Environment','307-GE - UL - 14',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Project Management','308-GE - UL - 15',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Knowledge Management','309-GE - UL - 16',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Corporate Governance','310-GE - UL - 17',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Management of Non-profit organizations','311-GE - UL - 18',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Business to Business Marketing','312-SE ? IL - MKT- 07',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'International Marketing','313-SE ? IL - MKT- 08',4,3);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Digital Marketing - II','314-SE ? IL - MKT- 09',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Marketing of Financial Services - II','315-SE ? IL - MKT- 10',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Marketing Analytics','316-SE ? IL - MKT- 11',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Marketing of High Technology Products','317-SE ? IL - MKT- 12',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Behavioural Finance','312-SE ? IL - FIN - 09',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Technical Analysis of Financial Markets','312-SE ? IL - FIN - 10',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Commodities Markets','314-SE ? IL - FIN - 11',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Indirect Taxation','315-SE ? IL - FIN ? 12',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Corporate Financial Restructuring','316-SE ? IL - FIN ? 13',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Financial Modeling','317-SE ? IL - FIN - 14',4,3);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Digital Banking','318-SE ? IL - FIN ? 15',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Treasury Management','319-SE ? IL - FIN ? 16',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Project Finance and Trade Finance','320-SE ? IL - FIN ? 17',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Insurance Laws & Regulations','321-SE ? IL - FIN ? 18',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Marine Insurance','322-SE ? IL - FIN ? 19',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Fire Insurance','323-SE ? IL - FIN ? 20',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Talent Management','312-SE ? IL - HRM - 07',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Psychometric Testing and Assessment','312-SE ? IL - HRM - 08',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'HR perspective in Mergers and Acquisition','314-SE ? IL - HRM - 09',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'International HR','315-SE ? IL - HRM - 10',4,3);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Mentoring and Coaching','316-SE ? IL - HRM - 11',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Compensation and Reward management','317-SE ? IL - HRM - 12',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Performance Management System','318-SE ? IL - HRM - 13',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Change Management & New Technologies in HRM','319-SE ? IL - HRM - 14',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Manufacturing Resource Planning','312-SE ? IL - OSCM ? 07',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Sustainable Supply Chains','313-SE ? IL - OSCM ? 08',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Business Excellence','314-SE ? IL - OSCM ? 09',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Toyota Production System','315-SE ? IL - OSCM ? 10',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Operations and Services Strategy','316-SE ? IL - OSCM ? 11',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Six Sigma for Operations','317SE ? IL - OSCM ? 12',4,3);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Social Media, Web & Text Analytics','312-SE ? IL - BA ? 06',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Industrial Internet of Things','313-SE ? IL - BA ? 07',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Supply Chain Analytics','314-SE ? IL - BA ? 08',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Cognos Analytics','315-SE ? IL - BA ? 09',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Predictive Modelling using SPSS Modeler','316-SE ? IL - BA ? 10',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'E commerce Analytics - I','317SE ? IL - BA ? 11',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Introduction to Cyber Security ? III','392',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Skill Development - I','394',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Introduction to Constitution','395',4,3),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Enterprise Performance Management','401-GC ? 14',4,4);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Indian Ethos & Business Ethics','402-GC ? 15',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Marketing 4.0','403-SC ? MKT- 05',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Marketing Strategy','404-SC ? MKT- 06',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Financial Laws','403-SC ? FIN - 05',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Current Trends & Cases in Finance','404-SC ? FIN - 06',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Organizational Diagnosis & Development','403-SC ? HRM - 05',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Current Trends & Cases in Human Resource Management','404-SC ? HRM - 06',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'E Supply Chains & Logistics','403-SC ? OSCM - 05',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Industry 4.0','404-SC ? OSCM - 06',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Economics of Network Industries','403-SC ? BA - 05',4,4);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Artificial Intelligence in Business Applications','404-SC ? BA - 06',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Global Strategic Management','405-GE - UL - 19',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Technology Competition and Strategy','406-GE - UL - 20',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Cyber Laws','407-GE - UL - 21',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Corporate Social Responsibility & Sustainability','408-GE - UL - 22',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Customer Relationship Management','409-SE ? IL - MKT- 13',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Rural & Agriculture Marketing','410-SE ? IL - MKT- 14',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Tourism & Hospitality Marketing','411-SE ? IL - MKT- 15',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Retail Marketing','412-SE ? IL - MKT- 16',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Retailing Analytics','413-SE ? IL - MKT- 17',4,4);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Marketing Management',1,'Marketing to Emerging Markets & Bottom of the Pyramid','414-SE ? IL - MKT- 18',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Fixed Income Securities','409-SE ? IL - FIN ? 21',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Business Valuation','410-SE ? IL - FIN ? 22',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Risk Management','411-SE ? IL - FIN ? 23',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Strategic Cost Management','412-SE ? IL - FIN ? 24',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Rural and Micro Finance','413-SE ? IL - FIN ? 25',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Reinsurance','414-SE ? IL - FIN - 26',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Finacial Management',1,'Agricultural Insurance','415-SE ? IL - FIN ? 27',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Labour Legislation','409-SE ? IL - HRM - 15',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Designing HR Policies','410-SE ? IL - HRM - 16',4,4);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Labour Economics and Costing','411-SE ? IL - HRM - 17',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Best Practices in HRM','412-SE ? IL - HRM - 18',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Employee Engagement and Ownership','413-SE ? IL - HRM - 19',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'Leadership and Succession Planning','414-SE ? IL - HRM ? 20',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Human Resource Management',1,'E - HRM','415-SE ? IL - HRM - 21',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Enterprise Resource Planning','409-SE ? IL - OSCM ? 14',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'World Class Manufacturing','410-SE ? IL - OSCM ? 15',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Supply Chain Strategy','411-SE ? IL - OSCM ? 16',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Financial Perspectives in Operations Management','412-SE ? IL ? OSCM ? 17',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Facilities Planning','413-SE ? IL - OSCM ? 18',4,4);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Purchasing and Supplier Relationship Management','414-SE ? IL - OSCM ? 19',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Operations and Supply Chain Management',1,'Strategic Supply Chain Management','415-SE ? IL - OSCM - 20',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'E Commerce Analytics - II','409-SE ? IL - BA - 13',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Healthcare Analytics','410-SE ? IL - BA - 14',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Watson','411-SE ? IL - BA ? 15',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Business Analytics',1,'Scala and Spark','412-SE ? IL - BA ? 16',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Rural And Agri -Business Management (RABM)',1,'Agriculture and Indian Economy','1-SC ? RABM ? 01',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Rural And Agri -Business Management (RABM)',1,'ICT for Agriculture Management','2-SC ? RABM ? 02',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Rural And Agri -Business Management (RABM)',1,'Rural Credit and Finance','1-SE ? RABM ? 03',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Rural And Agri -Business Management (RABM)',1,'Rural Marketing - I','2-SE ? RABM ? 04',4,4);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Rural And Agri -Business Management (RABM)',1,'Agri ? Entrepreneurship','3-SE? RABM ? 05',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Rural And Agri -Business Management (RABM)',1,'Rural Marketing II','4-SE ? RABM ? 06',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Pharma And Health Care Management (PHCM)',1,'Fundamentals of Pharma and Healthcare Management','1-SC ? PHCM- 01',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Pharma And Health Care Management (PHCM)',1,'Pharma and healthcare regulatory environment in India','2-SC ? PHCM- 02',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Pharma And Health Care Management (PHCM)',1,'Strategic Planning & Healthcare Management','1-SE ? PHCM- 03',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Pharma And Health Care Management (PHCM)',1,'Information Technology in Pharma and Healthcare','2-SE ? PHCM- 04',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Pharma And Health Care Management (PHCM)',1,'Pharmaceutical Import and Export','3-SE ? PHCM- 05',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Pharma And Health Care Management (PHCM)',1,'Entrepreneurship in Pharma and Healthcare','4-SE ? PHCM- 06',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Tourism & Hospitality Management (THM)',1,'Fundamentals of Hospitality Management','1-SC ? THM ? 01',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Tourism & Hospitality Management (THM)',1,'Tourism & Travel Management','2-SC ? THM - 02',4,4);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Tourism & Hospitality Management (THM)',1,'Event Management','1-SE ? THM - 03',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Tourism & Hospitality Management (THM)',1,'Tourism Planning & Development','2-SE ? THM - 04',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Tourism & Hospitality Management (THM)',1,'Strategic Hospitality Management','3-SE ? THM - 05',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Tourism & Hospitality Management (THM)',1,'Revenue Management','4-SE ? THM - 06',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','International Business Management (IB)',1,'Import Export Documentation and Procedures','1-SC ? IB ? 01',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','International Business Management (IB)',1,'Global Trade and Logistics Management','2-SC ? IB - 02',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','International Business Management (IB)',1,'Cross Cultural Management and Global Leadership','1-SE ? IB - 03',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','International Business Management (IB)',1,'International Business and Employment Laws','2-SE ? IB - 04',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','International Business Management (IB)',1,'Global Competitiveness, Value Chains and Alliances','3-SE ? IB- 05',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','International Business Management (IB)',1,'International Banking and Foreign Exchange Management','4-SE ? IB- 06',4,4);
INSERT INTO subject_entity (created_at,created_by,update_by,updated_at,version,pattern,specialization,status,subject,subject_code,class_id,semester_id) VALUES
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Cyber Security ? IV','492',4,4),
	 (NULL,NULL,NULL,NULL,NULL,'2019','Management',1,'Skill Development - II','494',4,4);
